name: "Cast to Farcaster"
description: "Cast to Farcaster"
inputs:
    message:
        description: "Message to cast"
        required: true
    signer-uuid:
        description: "Signer UUID required to cast on behalf of a profile"
        required: true
    neynar-api-key:
        description: "Neynar API Key to cast"
        required: true
    release-url:
        description: "Url to Release Details Page"
runs:
    using: "node20"
    main: "main.js"
